export const FOCUS_PERIOD_FIELDS = {
  SET_TITLE: 'SET_TITLE',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  SET_START_DATE: 'SET_START_DATE',
  SET_END_DATE: 'SET_END_DATE',
  SET_TITLE_INVALID: 'SET_TITLE_INVALID'
};
