export const GROUP_FIELDS = {
    SET_NAME: 'SET_NAME',
    SET_NAME_INVALID: 'SET_NAME_INVALID',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    // SET_DESCRIPTION_INVALID: 'SET_DESCRIPTION_INVALID',
    // SET_MEMBERS: 'SET_MEMBERS',
    SET_ALL_USERS: 'SET_ALL_USERS',
    SET_SELECTED_MEMBERS: 'SET_SELECTED_MEMBERS'
}