export const ISSUE_TRACKER = {
  BUG: 1,
  FEATURE: 2,
  SUPPORT: 3,
  USER_STORY: 4,
  USER_STORY_CLOSED: 5,
  MEETING: 6,
  TEST_CREATE: 7,
  TEST_ANALYSIS: 9,
  PLANNING: 10,
  //EPIC: 12,
  CODE_REVIEW: 14
};