const ISSUE_ACTION = {
  ISSUE_CREATE: 'CREATE',
  ISSUE_EDIT: 'EDIT',
  ISSUE_VIEW: 'VIEW',
  ISSUE_UPDATE_STATUS: 'UPDATE_STATUS',
  ISSUE_HISTORY: 'HISTORY',
  US_CREATE: 'US_CREATE',
  US_EDIT: 'US_EDIT',
  US_VIEW: 'US_VIEW',
  US_UPDATE_STATUS: 'US_UPDATE_STATUS',
  US_HISTORY: 'US_HISTORY'
};

export default ISSUE_ACTION;