export const PROJECT_REDUCER_ACTION = {
    SET_NAME: 'SET_NAME',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_NAME_INVALID: 'SET_NAME_INVALID',
    SET_DESCRIPTION_INVALID: 'SET_DESCRIPTION_INVALID',
    SET_MEMBERS: 'SET_MEMBERS',
};