export const SERVER_EVENT_TYPES = {
  UPDATE_ISSUES: 'UPDATE_ISSUES',
  UPDATE_PROJECTS: 'UPDATE_PROJECTS',
  UPDATE_STORIES: 'UPDATE_STORIES',
  UPDATE_EVERYTHING: 'UPDATE_EVERYTHING',
  UPDATE_MEMBERS: 'UPDATE_MEMBERS',
  UPDATE_SPRINTS: 'UPDATE_SPRINTS',
  UPDATE_FOCUS_PERIOD: 'UPDATE_FOCUS_PERIOD',
};
