export const SPRINT_REDUCER_ACTION = {
    SET_NAME: 'SET_NAME',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_NAME_INVALID: 'SET_NAME_INVALID',
    SET_DESCRIPTION_INVALID: 'SET_DESCRIPTION_INVALID',
    SET_PROJECT: 'SET_PROJECT',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE',
    SET_START_DATE_INVALID: 'SET_START_DATE_INVALID',
    SET_END_DATE_INVALID: 'SET_END_DATE_INVALID',
};